import type { Metadata } from 'next'
import '@/app/styles/global.scss'
import Link from 'next/link'
import Navbar from './components/Navbar/Navbar'
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <Link href={'/'}>Home</Link>
        {children}
      </body>
    </html>
  )
}
